 CREATE TABLE DEPT (DNO DECIMAL(4) NOT NULL, DNAME CHAR(20) NOT NULL, DEAN CHAR(30), PRIMARY KEY (DNO), UNIQUE (DNAME));
 CREATE TABLE EMP (ENO DECIMAL(4) NOT NULL, ENAME CHAR(20) NOT NULL, EDESC CHAR(30), DNO DECIMAL(4) NOT NULL, DNAME CHAR(20), BTH_DATE  DECIMAL(6) NOT NULL, PRIMARY KEY (ENO), UNIQUE (ENAME,BTH_DATE), FOREIGN KEY (DNO) REFERENCES DEPT(DNO), FOREIGN KEY (DNAME) REFERENCES DEPT(DNAME));
 CREATE TABLE EXPERIENCE (EXP_NAME CHAR(20), BTH_DATE DECIMAL(6), WK_DATE  DECIMAL(6), DESCR CHAR(40), FOREIGN KEY (EXP_NAME,BTH_DATE) REFERENCES EMP(ENAME,BTH_DATE)); 
 CREATE TABLE STAFF_P (EMPNUM   CHAR(3) NOT NULL,EMPNAME  CHAR(20), GRADE    DECIMAL(4), CITY     CHAR(15), UNIQUE  (EMPNUM));
 CREATE TABLE PROJ_P (PNUM     CHAR(3) NOT NULL, PNAME    CHAR(20), PTYPE    CHAR(6), BUDGET   DECIMAL(9), CITY     CHAR(15), UNIQUE   (PNUM)); 
 CREATE TABLE WORKS_P (EMPNUM   CHAR(3) REFERENCES STAFF_P(EMPNUM), PNUM     CHAR(3), HOURS    DECIMAL(5), FOREIGN KEY (PNUM) REFERENCES PROJ_P(PNUM));

 CREATE TABLE MID1 (P_KEY DECIMAL(4) NOT NULL UNIQUE, F_KEY DECIMAL(4) REFERENCES MID1(P_KEY)); 
 CREATE TABLE ACR_SCH_P(P1 DECIMAL(4) NOT NULL UNIQUE, P2 CHAR(4));
 CREATE TABLE TAB5(F15 CHAR(3), F5 CHAR(4), FOREIGN KEY (F15) REFERENCES STAFF_P(EMPNUM));
