SET NAMES ASCII;
CREATE DATABASE 'test.fdb' ;
CREATE DOMAIN test VARCHAR(63);

ALTER DOMAIN test SET DEFAULT 'test string';
COMMIT;
SELECT RDB$FIELD_NAME, RDB$DEFAULT_SOURCE FROM rdb$fields WHERE RDB$FIELD_NAME='TEST';

DROP DATABASE;

