CREATE DATABASE 'test.fdb' ;
CREATE DOMAIN test VARCHAR(63) CHECK(VALUE LIKE 'TE%');

ALTER DOMAIN test DROP CONSTRAINT;
COMMIT;
SELECT RDB$FIELD_NAME, RDB$VALIDATION_SOURCE FROM rdb$fields WHERE RDB$FIELD_NAME='TEST';

DROP DATABASE;

