CREATE DATABASE 'test.fdb' ;
SET NAMES ASCII;
CREATE DOMAIN test VARCHAR(63) DEFAULT 'test string';

ALTER DOMAIN test DROP DEFAULT;
COMMIT;
SELECT RDB$FIELD_NAME, RDB$DEFAULT_SOURCE FROM rdb$fields WHERE RDB$FIELD_NAME='TEST';

DROP DATABASE;

