CREATE DATABASE 'test.fdb' ;

SET TERM ^;
CREATE PROCEDURE test( 
  p1 SMALLINT, p2 INTEGER, p3 FLOAT, p4 DOUBLE PRECISION, p5 DECIMAL(9,3), p6 NUMERIC(10,4),
  p7 DATE, p8 TIME, p9 TIMESTAMP, p10 CHAR(40), p11 VARCHAR(60), p12 NCHAR(70))
AS
BEGIN
  POST_EVENT 'Test';
END ^
SET TERM ;^
SHOW PROCEDURE test;

DROP DATABASE;

