CREATE DATABASE 'test.fdb' ;
CREATE TABLE tb(id INT);
INSERT INTO tb VALUES(10);
INSERT INTO tb VALUES(10);
INSERT INTO tb VALUES(20);
COMMIT;

DELETE FROM tb WHERE id>10;
SELECT * FROM tb;

DROP DATABASE;

