SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab3.sql;
INPUT ddl/input/sun-tab3-refresh.sql;

-- TEST:0438 (partial-NULL F.K.) F.K. INSERT supported!
 DELETE FROM EXPERIENCE WHERE DESCR = 'Car Mechanic'; 
 INSERT INTO EXPERIENCE VALUES('Tom',NULL,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES('Yolanda',NULL,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES(NULL,112156,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES(NULL,062068,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES(NULL,NULL,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES('Lilian',112156,NULL,'Car Mechanic');
 INSERT INTO EXPERIENCE VALUES('Tom',052744,NULL,'Car Mechanic');
-- PASS:0438 If RI ERROR, parent missing, 0 rows inserted?

 INSERT INTO EXPERIENCE VALUES('Yolanda',040523,NULL,'Car Mechanic');
-- PASS:0438 If RI ERROR, parent missing, 0 rows inserted?

 INSERT INTO EXPERIENCE VALUES('Yolanda',062968,NULL,'Car Mechanic');
-- PASS:0438 If RI ERROR, parent missing, 0 rows inserted?

 SELECT EXP_NAME, BTH_DATE FROM EXPERIENCE WHERE EXP_NAME IS NOT NULL AND BTH_DATE IS NOT NULL AND DESCR = 'Car Mechanic'; 
-- PASS:0438 If 1 row is seleced with values?
-- PASS:0438 EXP_NAME = 'Lilian' and BTH_DATE = 112156?
 
 SELECT COUNT(*) FROM EXPERIENCE WHERE DESCR = 'Car Mechanic';
-- PASS:0438 If count = 6?

INPUT ddl/input/sun-tab3-refresh.sql;

-- TEST:0439 (partial-NULL F.K.) F.K. UPDATE supported!
 INSERT INTO EXPERIENCE VALUES('Lilian',NULL,NULL,'Soccer Player');
 INSERT INTO EXPERIENCE VALUES('David',NULL,NULL,'Monk');
 INSERT INTO EXPERIENCE VALUES(NULL,NULL,NULL,'Fireman');
 INSERT INTO EXPERIENCE VALUES(NULL,NULL,NULL,'Artist');
 UPDATE EXPERIENCE SET BTH_DATE = 040523 WHERE EXP_NAME = 'Lilian' AND DESCR = 'Soccer Player';
 UPDATE EXPERIENCE SET EXP_NAME = NULL WHERE DESCR = 'Photographer';
 UPDATE EXPERIENCE SET EXP_NAME = NULL ,BTH_DATE = NULL WHERE DESCR = 'Fashion Model'; 
 UPDATE EXPERIENCE SET BTH_DATE = 101024 WHERE EXP_NAME = 'David' AND DESCR = 'Monk'; 
 UPDATE EXPERIENCE SET EXP_NAME = 'Mary', BTH_DATE = 121245 WHERE DESCR = 'Fireman'; 
 UPDATE EXPERIENCE SET EXP_NAME = 'Dick' , BTH_DATE = 020454 WHERE DESCR = 'Artist'; 
 SELECT EXP_NAME, DESCR, BTH_DATE FROM EXPERIENCE ORDER BY EXP_NAME, BTH_DATE; 
 SELECT EXP_NAME, DESCR, BTH_DATE FROM EXPERIENCE ORDER BY EXP_NAME, BTH_DATE; 
-- PASS:0439 If 'David' the 'Monk' has BTH_DATE = 101024 ?
-- PASS:0439 If 3 rows with 'Lilian' have BTH_DATE = 112156 or NULL?
-- PASS:0439 If 'Mary' is a 'Fireman' with BTH_DATE = 121245?
-- PASS:0439 If EXP_NAME is NULL for 'Photographer'?
-- PASS:0439 If EXP_NAME and BTH_DATE are NULL for 'Fashion Model'?
-- PASS:0439 If EXP_NAME is NULL for 'Artist'?

 DELETE FROM EXPERIENCE WHERE EXP_NAME = 'Joseph' OR EXP_NAME = 'John'; 
 INSERT INTO EXPERIENCE VALUES('John',NULL,NULL,'Gardener');
 INSERT INTO EXPERIENCE VALUES('Joseph',NULL,NULL,'Snake Charmer');
 DELETE FROM EMP WHERE ENAME = 'Joseph';
 UPDATE EMP SET ENAME = 'Joan' WHERE EDESC = 'Fraction'; 
 SELECT ENAME FROM EMP WHERE DNAME = 'Education'; 
 SELECT DNAME FROM EMP WHERE ENAME = 'Joan'; 

DROP DATABASE;
