SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab1.sql;

 UPDATE STAFF_M SET EMPNUM = 'E9' WHERE EMPNUM = 'E2'; 
 SELECT COUNT(*) FROM STAFF_M WHERE EMPNUM = 'E2';
 UPDATE PROJ_M SET MGR = 'E9' WHERE MGR = 'E3';
 SELECT COUNT(*) FROM PROJ_M WHERE MGR = 'E3';
 UPDATE PROJ_M SET MGR = 'E5' WHERE MGR = 'E3';
 SELECT COUNT(*) FROM PROJ_M WHERE MGR = 'E5';
 INSERT INTO STAFF_M VALUES('E8','Alice',12,'Deale','P9');
 SELECT COUNT(*) FROM STAFF_M WHERE PRI_WK = 'P9';

DROP DATABASE;
