SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab3.sql;
INPUT ddl/input/sun-tab3-refresh.sql;
COMMIT;
 CREATE TABLE TTT(P1 DECIMAL(4) NOT NULL UNIQUE,P2 CHAR(4));
 GRANT SELECT ON TTT TO sun;
 CREATE TABLE ACR_SCH_F(F1 DECIMAL(4), F2 CHAR(4), FOREIGN KEY (F1) REFERENCES ACR_SCH_P(P1));
-- TEST:0382 (ref. acr. sch.) with GRANT OPTION, insert!

 INSERT INTO ACR_SCH_F VALUES(1,'DOG');

 INSERT INTO ACR_SCH_F VALUES(2,'PIG');
-- PASS:0382 If RI ERROR, parent missing, 0 rows inserted?

 SELECT COUNT(*) FROM ACR_SCH_F; 
-- PASS:0382 If count = 1?

DROP DATABASE;
