SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

 CREATE TABLE STAFF10 (EMPNUM    CHAR(3) NOT NULL, EMPNAME  CHAR(20), GRADE DECIMAL(4), CITY   CHAR(15), PRIMARY KEY (EMPNUM), CHECK (GRADE NOT IN (5,22)));
 INSERT INTO STAFF10 VALUES('E3','Susan',11,'Hawaii');
 UPDATE STAFF10 SET GRADE = 5WHERE EMPNUM = 'E3';
 SELECT COUNT(*) FROM STAFF10 WHERE GRADE = 11;
 CREATE TABLE STAFF11 (EMPNUM CHAR(3) NOT NULL PRIMARY KEY, EMPNAME  CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), CHECK (GRADE NOT IN (5,22) AND EMPNAME NOT LIKE 'T%'));
 INSERT INTO STAFF11 VALUES('E3','Susan',11,'Hawaii');
 UPDATE STAFF11 SET GRADE = 5 WHERE EMPNUM = 'E3';
 UPDATE STAFF11 SET EMPNAME = 'Tom' WHERE EMPNUM = 'E3'; 
 SELECT COUNT(*) FROM STAFF11 WHERE EMPNAME = 'Susan' AND GRADE = 11;
 CREATE TABLE STAFF12 (EMPNUM    CHAR(3) NOT NULL,EMPNAME  CHAR(20),GRADE DECIMAL(4),CITY   CHAR(15),PRIMARY KEY (EMPNUM),CHECK (NOT GRADE IN (5,22)AND NOT EMPNAME LIKE 'T%'));
 INSERT INTO STAFF12 VALUES('E3','Susan',11,'Hawaii');
 UPDATE STAFF12 SET GRADE = 5 WHERE EMPNUM = 'E3';
 SELECT COUNT(*) FROM STAFF12 WHERE GRADE = 11;
 CREATE TABLE STAFF15 (EMPNUM CHAR(3), EMPNAME  CHAR(20) NOT NULL, GRADE DECIMAL(4), CITY CHAR(15));
 INSERT INTO STAFF15 VALUES('E1','Alice',52,'Deale');
 UPDATE STAFF15 SET EMPNAME = NULL WHERE EMPNUM = 'E1';
 SELECT COUNT(*) FROM STAFF15 WHERE EMPNAME = 'Alice';

DROP DATABASE;
