SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab1.sql;

 INSERT INTO PROJ_M VALUES ('P7','IAC','Head',30000,'Alexdra','E5');
 INSERT INTO PROJ_M VALUES ('P8','IBM','Head',30000,'Alexdra','E5');
 SELECT COUNT(*) FROM PROJ_M WHERE MGR = 'E5';
 delete from proj_m where pNum in ('p7', 'p8');
 DELETE FROM STAFF_M WHERE EMPNUM='E2';
 SELECT EMPNUM FROM STAFF_M WHERE EMPNUM = 'E2';
 UPDATE STAFF_M SET EMPNUM = 'E9' WHERE EMPNUM = 'E1';
 SELECT EMPNUM FROM STAFF_M WHERE EMPNUM = 'E9'; 

DROP DATABASE;
