SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab2.sql;
INPUT ddl/input/sun-tab2-refresh.sql;

 INSERT INTO SIZ1_P VALUES('E1','TTT',1,'SSS',10,'RRR','HHH','ZZZ',6);
 SELECT COUNT(*) FROM SIZ1_P WHERE S1 = 'E1';
 INSERT INTO SIZ1_F VALUES('E1','TTT',1,'SSS',19,'RRS','TTT',5,6);
 SELECT COUNT(*) FROM SIZ1_F WHERE F6 = 'RRS';

DROP DATABASE;
