SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab2.sql;
INPUT ddl/input/sun-tab2-refresh.sql;
 INSERT INTO SIZ3_F VALUES ('  F','  D',3,'  E',4,'  F','  G',5,6,7,'TTT');
 INSERT INTO SIZ3_F VALUES ('  D','  E',4,'  F',5,'  G','  H',6,7,100,'TTT');
 SELECT COUNT(*) FROM SIZ3_F;

INPUT ddl/input/sun-tab2-refresh.sql;
 DELETE FROM SIZ3_P1 WHERE F1 = '  A';
 SELECT F1 FROM SIZ3_P1 WHERE F1 = '  A';
 UPDATE SIZ3_P1 SET F1 = '  Z' WHERE F1 = '  A'; 
 UPDATE SIZ3_P10 SET F1 = 100 WHERE F1 = 8; 
 SELECT COUNT(*) FROM SIZ3_P1 WHERE F1 = '  A';
 SELECT COUNT(*) FROM SIZ3_P1 WHERE F1 = '  A'; 
 UPDATE SIZ3_P1 SET F1 = '  B'WHERE F1 = '  A';
 SELECT COUNT(*) FROM SIZ3_P1 WHERE F1 = '  A';
 UPDATE SIZ3_F SET P1 = '  Z' WHERE P1 = '  A';
 SELECT COUNT(*) FROM SIZ3_F WHERE P1 = '  A';

DROP DATABASE;
