SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/sun-tab1.sql;

 INSERT INTO STAFF_C VALUES('E1','Alice',12,'Deale',NULL);
 INSERT INTO STAFF_C VALUES('E2','Betty',10,'Vienna','E1');
 INSERT INTO STAFF_C VALUES('E3','Carmen',13,'Vienna','E2');
 INSERT INTO STAFF_C VALUES('E4','Don',12,'Deale','E2');
 INSERT INTO STAFF_C VALUES('E5','Don',12,'Deale','E1');
 INSERT INTO STAFF_C VALUES('E6','Tom',14,'Gettysburg','E5');
 INSERT INTO STAFF_C VALUES('E7','Kingdom',18,'Gettysburg','E7');
 INSERT INTO STAFF_C VALUES('E8','Alice',12,'Deale','E1');
 SELECT COUNT(*) FROM STAFF_C WHERE MGR = 'E1';
 delete from staff_c where empnum = 'e8';
 DELETE FROM STAFF_C WHERE EMPNUM='E1';
 SELECT EMPNUM FROM STAFF_C WHERE EMPNUM = 'E1';
 UPDATE STAFF_C SET MGR = NULL;
 DELETE FROM STAFF_C;
 INSERT INTO STAFF_C VALUES('E1','Alice',12,'Deale',NULL);
 UPDATE STAFF_C SET EMPNUM = 'E9' WHERE EMPNUM = 'E1'; 
 SELECT EMPNUM FROM STAFF_C WHERE EMPNUM = 'E9';

DROP DATABASE;
