SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;

 SELECT ALL EMPNUM FROM WORKS WHERE HOURS = 12;
-- PASS:0016 If 2 rows are selected and both EMPNUMs are 'E1'? SELECT EMPNUM FROM WORKS WHERE HOURS = 12;

 SELECT EMPNUM FROM WORKS WHERE HOURS = 12;
-- TEST:0164 SELECT:default is ALL, not DISTINCT!

 SELECT DISTINCT EMPNUM FROM WORKS WHERE HOURS = 12;
-- PASS:0017 If 1 row is selected and EMPNUM = 'E1'?

 SELECT EMPNUM,PNUM FROM WORKS WHERE EMPNUM = 'E16';
-- PASS:0018 If 0 rows selected, SQLCODE = 100, end of data?

 SELECT EMPNUM,HOURS FROM WORKS WHERE EMPNUM = 'E1' AND PNUM = 'P4';
-- PASS:0019 If HOURS = 20 ? 

 INSERT INTO WORKS VALUES('E18','P18',NULL);
 SELECT EMPNUM,HOURS FROM WORKS WHERE EMPNUM='E18' AND PNUM='P18';
-- PASS:0020 If EMPNUM = 'E18' and HOURS is NULL?

DROP DATABASE;
