SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;

 SELECT EMPNUM,HOURS FROM WORKS WHERE PNUM='P2' ORDER BY EMPNUM DESC;
-- PASS:0001 If 4 rows selected and last EMPNUM = 'E1'?

 SELECT EMPNUM,HOURS FROM WORKS WHERE PNUM='P2' ORDER BY 2 ASC;
-- PASS:0002 If 4 rows selected and last HOURS = 80?

 SELECT EMPNUM,HOURS FROM WORKS WHERE PNUM = 'P2' ORDER BY 2 DESC,EMPNUM DESC;
-- PASS:0003 If 4 rows selected and last EMPNUM = 'E1'?

 SELECT WORKS.EMPNUM FROM WORKS WHERE WORKS.PNUM = 'P2' UNION SELECT STAFF.EMPNUM FROM STAFF WHERE STAFF.GRADE=13 ORDER BY 1 DESC;
-- PASS:0004 If 5 rows selected and last EMPNUM = 'E1'?

 SELECT WORKS.EMPNUM FROM WORKS WHERE WORKS.PNUM = 'P2' UNION ALL SELECT STAFF.EMPNUM FROM STAFF WHERE STAFF.GRADE = 13;
-- PASS:0005 If 6 rows selected?

 SELECT EMPNAME,PNUM,HOURS FROM STAFF,WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM UNION SELECT EMPNAME,PNUM,HOURS FROM STAFF,WORKS WHERE NOT EXISTS (SELECT HOURS FROM WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM);

-- TEST:0158 SELECT with UNION and NOT EXISTS subquery!
 SELECT PNUM,EMPNUM,HOURS FROM WORKS WHERE HOURS=80 UNION SELECT PNUM,EMPNUM,HOURS FROM WORKS WHERE HOURS=40 UNION SELECT PNUM,EMPNUM,HOURS FROM WORKS WHERE HOURS=20 ORDER BY 3,1;
-- Expected output:
--
-- EMPNAME PNUM HOURS
-- ==================== ====== ============
-- 
-- Alice P1 40
-- Alice P2 20
-- Alice P3 80
-- Alice P4 20
-- Alice P5 12
-- Alice P6 12
-- Betty P1 40
-- Betty P2 80
-- Carmen P2 20
-- Don P2 20
-- Don P4 40
-- Don P5 80
-- Ed P1 40
-- Ed P2 20
-- Ed P2 80
-- Ed P3 80
-- Ed P4 20
-- Ed P4 40
-- Ed P5 12
-- Ed P5 80
-- Ed P6 12
 

DROP DATABASE;
