SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

 CREATE TABLE WORKS1(EMPNUM    CHAR(3) NOT NULL, PNUM    CHAR(3) NOT NULL, HOURS   DECIMAL(5), UNIQUE(EMPNUM, PNUM));
 DELETE FROM VTABLE;
 INSERT INTO VTABLE VALUES (80, 100, 100, 100, 100.0);
 INSERT INTO VTABLE VALUES (40, 200, 100, 100, 100.0);
 SELECT PNUM FROM WORKS WHERE EMPNUM = 'E1' AND HOURS IN (SELECT COL1 FROM VTABLE WHERE  COL1 > 50);
-- PASS:0406 If PNUM = 'P3'?

ROLLBACK WORK;

 DELETE FROM WORKS1;
 INSERT INTO WORKS1 SELECT * FROM WORKS;
 UPDATE WORKS1 SET PNUM = EMPNUM, EMPNUM = PNUM, HOURS = (HOURS + 3) * HOURS;
-- integrity constraint violation

DROP DATABASE;
