SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;

 COMMIT;

-- TEST:0061 COMMIT work keeps changes to database!
 CREATE TABLE TEMP_S (EMPNUM  CHAR(3), GRADE DECIMAL(4), CITY CHAR(15));
 INSERT INTO TEMP_S SELECT EMPNUM, GRADE, CITY FROM STAFF;
 COMMIT;
 SELECT COUNT(*) FROM TEMP_S;
-- PASS:0061 If count = 5?
 DELETE FROM TEMP_S WHERE EMPNUM = 'E5';
 SELECT COUNT(*) FROM TEMP_S;
-- PASS:0062 If count = 4?
 ROLLBACK;
 SELECT COUNT(*) FROM TEMP_S;
 -- PASS:0062 If count = 5?

DROP DATABASE;
