SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

-- TEST:0518 CREATE VIEW with DISTINCT!

 CREATE VIEW DV1 AS SELECT DISTINCT HOURS FROM WORKS;
 CREATE TABLE BASE_VS1 (C1 INT, C2 INT);
 CREATE VIEW VS1 AS SELECT * FROM BASE_VS1 WHERE C1 = 0;
 CREATE VIEW VS2 AS SELECT A.C1 FROM BASE_VS1 A WHERE EXISTS (SELECT B.C2 FROM BASE_VS1 B WHERE B.C2 = A.C1);
 CREATE VIEW VS3 AS SELECT A.C2 FROM BASE_VS1 A WHERE A.C2 IN (SELECT B.C1 FROM BASE_VS1 B WHERE B.C1 < A.C2);
 CREATE VIEW VS4 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < ALL (SELECT B.C2 FROM BASE_VS1 B);
 CREATE VIEW VS5 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < SOME (SELECT B.C2 FROM BASE_VS1 B);
 CREATE VIEW VS6 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < ANY (SELECT B.C2 FROM BASE_VS1 B);

 SELECT COUNT(*) FROM DV1;
-- PASS:0518 If count = 4?

 SELECT HOURS FROM DV1 ORDER BY HOURS DESC;
-- PASS:0518 If 4 rows selected AND first HOURS = 80?
-- PASS:0518 AND second HOURS = 40 AND third HOURS = 20?
-- PASS:0518 AND fourth HOURS = 12?

 SELECT COUNT(*) FROM VS2 WHERE C1 = 0;
-- PASS:0519 If count = 2?
-- TODO: NIST says result should be 2, but we get back 0. wbo

 SELECT COUNT(*) FROM VS2 WHERE C1 = 1;
-- PASS:0519 If count = 2?
-- TODO: wbo - we get 0, but NIST says we should get 2.

 SELECT COUNT(*) FROM VS3;
-- PASS:0519 If count = 0?

 SELECT COUNT(*) FROM VS4;
-- PASS:0519 If count = 0?

 SELECT COUNT(*) FROM VS5;
-- PASS:0519 If count = 2?
-- TODO: NIST says we should get 2, but we got 0. wbo

 SELECT COUNT(*) FROM VS6;
-- PASS:0519 If count = 2?
-- TODO: NIST says result should be 2, but firebird returns 0

 CREATE TABLE CONCATBUF (ZZ CHAR(240));
 CREATE TABLE USIG (C1 INT, C_1 INT);
 CREATE TABLE U_SIG (C1 INT, C_1 INT);
 INSERT INTO USIG VALUES (0,2);
 INSERT INTO USIG VALUES (1,3);
 SELECT COUNT(*) FROM USIG WHERE C1 = 0;
-- PASS:0520 If count = 1?

 SELECT COUNT(*) FROM USIG WHERE C1 = 2;
-- PASS:0520 If count = 0?

 SELECT COUNT(*) FROM USIG WHERE C_1 = 0;
-- PASS:0520 If count = 0?

 SELECT COUNT(*) FROM USIG WHERE C_1 = 2;
-- PASS:0520 If count = 1?

 SELECT COUNT(*) FROM USIG WHERE C1 = 4;
-- PASS:0520 If count = 0?

 SELECT COUNT(*) FROM U_SIG WHERE C1 = 0;
-- PASS:0520 If count = 0?

 DELETE FROM U_SIG;
 INSERT INTO U_SIG VALUES (4,6);
 INSERT INTO U_SIG VALUES (5,7);
 SELECT COUNT(*) FROM U_SIG WHERE C1 = 4;
-- PASS:0520 If count = 1?

 SELECT COUNT(*) FROM STAFF U_CN WHERE U_CN.GRADE IN (SELECT UCN.GRADE FROM STAFF UCN WHERE UCN.GRADE > 10);
-- PASS:0520 If count = 4?

 SELECT COUNT(*) FROM STAFF WHERE GRADE > 10;
-- PASS:0520 If count = 4?

 SELECT COUNT(*) FROM STAFF WHERE GRADE < 10;
-- PASS:0520 If count = 0?

DROP DATABASE;
