SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;

-- TEST:0074 GROUP BY col with SELECT col., SUM!
 SELECT PNUM, SUM(HOURS) FROM WORKS GROUP BY PNUM;
-- PASS:0074 If 6 rows are selected?
-- PASS:0074 If PNUMs: 'P1', 'P2', 'P3', 'P4', 'P5', 'P6'?
-- PASS:0074 If SUM(HOURS) for 'P2' is 140 ?

-- TEST:0075 GROUP BY clause!
 SELECT EMPNUM FROM WORKS GROUP BY EMPNUM;
-- PASS:0075 If 4 rows are selected with EMPNUMs: 'E1','E2','E3','E4'?

-- TEST:0076 GROUP BY 2 columns!
 SELECT EMPNUM,HOURS FROM WORKS GROUP BY EMPNUM,HOURS;
-- PASS:0076 If 10 rows are selected and EMPNUM = 'E1' in 4 rows ?
-- PASS:0076 for 1 row EMPNUM = 'E1' and HOURS = 12?

-- TEST:0077 GROUP BY all columns with SELECT * !
 SELECT * FROM WORKS GROUP BY PNUM,EMPNUM,HOURS;
-- PASS:0077 If 12 rows are selected ?

-- TEST:0078 GROUP BY three columns, SELECT two!
 SELECT PNUM,EMPNUM FROM WORKS GROUP BY EMPNUM,PNUM,HOURS;
-- PASS:0078 If 12 rows are selected ?

-- TEST:0079 GROUP BY NULL value!
 INSERT INTO STAFF(EMPNUM,EMPNAME,GRADE) VALUES('E6','WANG',40);
 INSERT INTO STAFF(EMPNUM,EMPNAME,GRADE) VALUES('E7','SONG',50);
 SELECT SUM(GRADE) FROM STAFF WHERE CITY IS NULL GROUP BY CITY;
-- PASS:0079 If SUM(GRADE) = 90?
 DELETE FROM STAFF WHERE CITY IS NULL;
 SELECT COUNT(*) FROM STAFF;
-- PASS:0079 If count = 5?

DROP DATABASE;
