SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0037 DELETE without WHERE clause!
 SELECT COUNT(*) FROM STAFF;
 DELETE FROM STAFF;
 SELECT COUNT(*) FROM STAFF;
-- PASS:0037 If count = 0?
		
 ROLLBACK;

 SELECT COUNT(*) FROM STAFF;
 -- PASS:0037 If count = 5?

-- TEST:0038 DELETE with correlated subquery in WHERE clause!
 SELECT COUNT(*) FROM WORKS;
 DELETE FROM WORKS WHERE WORKS.PNUM IN (SELECT PROJ.PNUM FROM PROJ WHERE PROJ.PNUM=WORKS.PNUM AND PROJ.CITY='Tampa');
 SELECT COUNT(*) FROM WORKS;
-- PASS:0038 If count = 11?

 ROLLBACK;

 SELECT COUNT(*) FROM WORKS;
-- PASS:0038 If count = 12?

DROP DATABASE;
