SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

 CREATE TABLE WORKS1(EMPNUM    CHAR(3) NOT NULL, PNUM    CHAR(3) NOT NULL, HOURS   DECIMAL(5), UNIQUE(EMPNUM, PNUM));

-- TEST:0118 Monadic arithmetic operator +!
 SELECT +MAX(DISTINCT HOURS) FROM WORKS;
-- PASS:0118 If +MAX(DISTINCT HOURS) = 80?

-- TEST:0119 Monadic arithmetic operator -!
 SELECT -MAX(DISTINCT HOURS) FROM WORKS;
-- PASS:0119 If -MAX(DISTINCT HOURS) = -80?

-- TEST:0120 Value expression with NULL primary IS NULL!
 INSERT INTO WORKS1 SELECT * FROM WORKS;
 INSERT INTO WORKS1 VALUES('E9','P1',NULL);
 SELECT EMPNUM FROM WORKS1 WHERE HOURS IS NULL;
-- PASS:0120 If EMPNUM = 'E9'?
 INSERT INTO WORKS SELECT EMPNUM,'P9',20+HOURS FROM WORKS1 WHERE EMPNUM='E9';
 SELECT COUNT(*) FROM WORKS WHERE EMPNUM='E9';
-- PASS:0120 If count = 1 ?
 SELECT COUNT(*) FROM WORKS WHERE HOURS IS NULL;
-- PASS:0120 If count = 1 ?

-- TEST:0121 Dyadic operators +, -, *, /!
 SELECT COUNT(*) FROM VTABLE;
-- PASS:0121 If count = 4 ?
 SELECT +COL1+COL2 - COL3*COL4/COL1 FROM VTABLE WHERE COL1=10;
-- PASS:0121 If answer is -90?

-- TEST:0122 Divisor shall not be zero!
 SELECT COL2/COL1+COL3 FROM VTABLE WHERE COL4=3;
-- PASS:0122 If ERROR Number not Divisible by Zero?

-- TEST:0123 Evaluation order of expression!
 SELECT (-COL2+COL1)*COL3 - COL3/COL1 FROM VTABLE WHERE COL4 IS NULL;
-- PASS:0123 If Answer is 8999997 (plus or minus 0.5)?

DROP DATABASE;
