SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

-- TEST:0512 <value expression> for IN predicate!

 CREATE TABLE TEMP_OBSERV (YEAR_OBSERV  NUMERIC(4), CITY         CHAR(10), MAX_TEMP     NUMERIC(5,2), MIN_TEMP     NUMERIC(5,2));
 SELECT MIN(PNAME) FROM PROJ, WORKS, STAFF WHERE PROJ.PNUM = WORKS.PNUM AND WORKS.EMPNUM = STAFF.EMPNUM AND BUDGET - GRADE * HOURS * 100 IN (-4400, -1000, 4000);
-- PASS:0512 If PNAME = 'CALM'?

 SELECT CITY, COUNT(*) FROM PROJ GROUP BY CITY HAVING (MAX(BUDGET) - MIN(BUDGET)) / 2 IN (2, 20000, 10000) ORDER BY CITY DESC;
-- PASS:0512 If in first row: CITY = 'Vienna' AND count = 2?
-- PASS:0512 AND in second row: CITY = 'Deale' AND count = 3?

ROLLBACK WORK;

 DELETE FROM TEMP_OBSERV;
-- PASS:0513 If 1 row is inserted?
 INSERT INTO TEMP_OBSERV (YEAR_OBSERV) VALUES (9999);
-- PASS:0513 If 1 row is inserted?
 INSERT INTO TEMP_OBSERV (YEAR_OBSERV)VALUES (10000);
-- TODO: Comment doesn't match result!
-- PASS:0513 If ERROR, constraint violation, 0 rows inserted?
 UPDATE TEMP_OBSERV SET YEAR_OBSERV = -10000 WHERE YEAR_OBSERV = 9999;
-- TODO: Comment doesn't match result!
-- PASS:0513 If ERROR, constraint violation, 0 rows updated?
 INSERT INTO TEMP_OBSERV (YEAR_OBSERV, MAX_TEMP) VALUES (-9999, 123.4517);
-- PASS:0513 If 1 row is inserted?
 SELECT COUNT(*) FROM TEMP_OBSERV WHERE MAX_TEMP = 123.45 AND MAX_TEMP NOT BETWEEN 123.4516 AND 123.4518;
-- PASS:0513 If count = 1?
 INSERT INTO TEMP_OBSERV (YEAR_OBSERV, MAX_TEMP) VALUES (-9999, 1234.51);
-- TODO: Comment doesn't match result!
-- PASS:0513 If ERROR, constraint violation, 0 rows inserted?

ROLLBACK WORK;

 SELECT COUNT(*) FROM PROJ WHERE 24 * 1000 BETWEEN BUDGET - 5000 AND 50000 / 1.7;
-- PASS:0523 If count = 3?

 SELECT PNAME FROM PROJ WHERE 'Tampa' NOT BETWEEN CITY AND 'Vienna' AND PNUM > 'P2';
-- PASS:0523 If PNAME = 'IRM'?

 SELECT CITY, COUNT(*) FROM PROJ GROUP BY CITY HAVING 50000 + 2 BETWEEN 33000 AND SUM(BUDGET) - 20;
-- PASS:0523 If CITY = 'Deale' and count = 3?

 SELECT EMPNUM, GRADE*1000 FROM STAFF WHERE GRADE * 1000 > ANY (SELECT SUM(BUDGET) FROM PROJ GROUP BY CITY, PTYPE HAVING PROJ.CITY = STAFF.CITY);

DROP DATABASE;
