SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

-- TEST:0084 Data type CHAR(20)!
 CREATE TABLE AA (CHARTEST     CHAR(20));
 CREATE TABLE BB (CHARTEST     CHAR);
 CREATE TABLE CC (CHARTEST     CHARACTER(20));
 CREATE TABLE DD (CHARTEST     CHARACTER);
 CREATE TABLE EE (INTTEST     INTEGER);
 CREATE TABLE FF (INTTEST     INT);
 CREATE TABLE GG (REALTEST     REAL);
 CREATE TABLE HH (SMALLTEST  SMALLINT);
 CREATE TABLE II (DOUBLETEST  DOUBLE PRECISION);
 CREATE TABLE JJ (FLOATTEST  FLOAT);
 CREATE TABLE KK (FLOATTEST  FLOAT(32));
 CREATE TABLE LL (NUMTEST  NUMERIC(13,6));
 CREATE TABLE MM (NUMTEST  NUMERIC);
 CREATE TABLE MM2 (NUMTEST NUMERIC(10));
 CREATE TABLE NN (NUMTEST  NUMERIC(9));
 CREATE TABLE OO (NUMTEST  NUMERIC(9));
 CREATE TABLE PP (NUMTEST  DECIMAL(13,6));
 CREATE TABLE QQ (NUMTEST  DECIMAL);
 CREATE TABLE RR (NUMTEST  DECIMAL(8));
 CREATE TABLE SS (NUMTEST  DEC(13,6));

COMMIT;

 INSERT INTO AA VALUES('abcdefghijklmnopqrst');
-- PASS:0084 If 1 row is inserted?

 SELECT CHARTEST FROM AA;
-- PASS:0084 If CHARTEST = 'abcdefghijklmnopqrst' ?

ROLLBACK;

-- TEST:0173 Data type CHAR!
 INSERT INTO BB VALUES('a');
-- PASS:0173 If 1 row is inserted?
 SELECT CHARTEST FROM BB;
-- PASS:0173 If CHARTEST = 'a'?

ROLLBACK;

-- TEST:0085 Data type CHARACTER(20)!
 INSERT INTO CC VALUES('abcdefghijklmnopqrst');
-- PASS:0085 If 1 row is inserted?
 SELECT CHARTEST FROM CC;
-- PASS:0085 If CHARTEST = 'abcdefghijklmnopqrst'?

ROLLBACK;

 INSERT INTO DD VALUES('a');
-- PASS:0174 If 1 row is inserted?
 SELECT CHARTEST FROM DD;
-- PASS:0174 If CHARTEST = 'a'?

ROLLBACK;

-- TEST:0086 Data type INTEGER!
 INSERT INTO EE VALUES(123456);
-- PASS:0086 If 1 row is inserted?
 SELECT INTTEST FROM EE;
-- PASS:0086 If INTTEST = 123456?

ROLLBACK;

 INSERT INTO FF VALUES(123456);
-- PASS:0087 If 1 row is inserted?
 SELECT INTTEST FROM FF;
-- PASS:0087 If INTTEST = 123456?

ROLLBACK;

 INSERT INTO HH VALUES(123);
-- PASS:0089 If 1 row is inserted?
 SELECT * FROM HH;
-- PASS:0089 If SMALLTEST = 123?

ROLLBACK;

 INSERT INTO MM VALUES(7);
-- TEST:0175 Data type NUMERIC!
 SELECT * FROM MM;
-- PASS:0175 If NUMTEST = 7?

ROLLBACK;

-- TEST:0176 Data type NUMERIC(9), SELECT *!
 DELETE FROM NN;
 INSERT INTO NN VALUES(123456789);
 SELECT * FROM NN;
-- PASS:0176 If NUMTEST = 123456789 ?

 INSERT INTO OO VALUES(123456789);
 SELECT NUMTEST FROM OO;
-- PASS:0177 If NUMTEST = 123456789?

 INSERT INTO QQ VALUES(56);
 SELECT * FROM QQ;
-- PASS:0178 If NUMTEST = 56?

 INSERT INTO RR VALUES(12345678);
 SELECT * FROM RR;
-- PASS:0179 If NUMTEST = 12345678?

DROP DATABASE;
