SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

 CREATE TABLE BASE_VS1 (C1 INT, C2 INT);
 CREATE VIEW VS1 AS SELECT * FROM BASE_VS1 WHERE C1 = 0;
 CREATE VIEW VS2 AS SELECT A.C1 FROM BASE_VS1 A WHERE EXISTS (SELECT B.C2 FROM BASE_VS1 B WHERE B.C2 = A.C1);
 CREATE VIEW VS3 AS SELECT A.C2 FROM BASE_VS1 A WHERE A.C2 IN (SELECT B.C1 FROM BASE_VS1 B WHERE B.C1 < A.C2);
 CREATE VIEW VS4 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < ALL (SELECT B.C2 FROM BASE_VS1 B);
 CREATE VIEW VS5 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < SOME (SELECT B.C2 FROM BASE_VS1 B);
 CREATE VIEW VS6 AS SELECT A.C1 FROM BASE_VS1 A WHERE A.C1 < ANY (SELECT B.C2 FROM BASE_VS1 B);
 CREATE VIEW V_WORKS1 AS SELECT * FROM WORKS WHERE HOURS > 15 WITH CHECK OPTION;
 CREATE VIEW V_WORKS2 AS SELECT * FROM V_WORKS1 WHERE EMPNUM = 'E1' OR EMPNUM = 'E6';
 CREATE VIEW V_WORKS3 AS SELECT * FROM V_WORKS2 WHERE PNUM = 'P2' OR PNUM = 'P7' WITH CHECK OPTION;

-- TEST:0511 CHECK clauses in nested views (clarified in SQL-92)!

 INSERT INTO V_WORKS2 VALUES('E9','P7',13);
-- PASS:0511 If ERROR, view check constraint, 0 rows inserted?

 INSERT INTO V_WORKS2 VALUES('E7','P4',95);
-- PASS:0511 If 1 row is inserted?

 INSERT INTO V_WORKS3 VALUES('E8','P2',85);
-- has always worked since FB15, 6/16/2005, although nist says should fail.
-- PASS:0511 If ERROR, view check constraint, 0 rows inserted?

 INSERT INTO V_WORKS3	VALUES('E1','P7',90);
-- PASS:0511 If 1 row is inserted?

 INSERT INTO V_WORKS3 VALUES('E9','P2',10);
-- PASS:0511 If ERROR, view check constraint, 0 rows inserted?

 SELECT COUNT(*) FROM  WORKS WHERE EMPNUM = 'E9';
-- PASS:0511 If count = 0?

 SELECT COUNT(*) FROM  WORKS WHERE HOURS > 85;
-- PASS:0511 If count = 2?

 UPDATE V_WORKS3 SET EMPNUM = 'E12', HOURS = 222 WHERE EMPNUM = 'E1' AND PNUM = 'P2';
-- PASS:0511 If ERROR, view check constraint, 0 rows updated?
 INSERT INTO WORKS VALUES('E6','P2',55);

 UPDATE V_WORKS3 SET EMPNUM = 'E13', HOURS = 222 WHERE EMPNUM = 'E6' AND PNUM = 'P2';
-- PASS:0511 If ERROR, view check constraint, 0 rows updated?

 SELECT COUNT(*) FROM WORKS WHERE HOURS = 222;
-- have always gotten 2, but nist says should be 0.
-- PASS:0511 If count = 0?

DROP DATABASE;
