SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0281 Updatable VIEW with ALL, IN, BETWEEN!
 CREATE VIEW STAFFV1 AS SELECT * FROM STAFF WHERE  GRADE >= 12;
 CREATE VIEW STAFFV2 AS SELECT * FROM STAFF WHERE  GRADE >= 12 WITH CHECK OPTION;
 CREATE VIEW UPDATE_VIEW1 AS SELECT ALL CITY FROM PROJ;
 CREATE VIEW UPDATE_VIEW2 AS SELECT HOURS, EMPNUM, PNUM FROM WORKS WHERE HOURS IN (10, 20, 40);
 CREATE VIEW UPDATE_VIEW3 AS SELECT * FROM WORKS WHERE PNUM BETWEEN 'P2' AND 'P4' AND EMPNUM NOT BETWEEN 'E2' AND 'E3';
 CREATE VIEW UPDATE_VIEW4 AS SELECT PNUM, EMPNUM FROM WORKS WHERE PNUM LIKE '_2%';
 CREATE VIEW UPDATE_VIEW5 AS SELECT * FROM STAFF WHERE EMPNAME IS NOT NULL AND CITY IS NULL;
 CREATE VIEW UPDATE_VIEW6 AS SELECT EMPNAME, CITY, GRADE FROM STAFF WHERE EMPNAME >= 'Betty' AND EMPNUM < 'E35' OR CITY <= 'Deale' AND GRADE > 12 OR GRADE = 13 AND CITY <> 'Akron';
 CREATE VIEW UPDATE_VIEW7 AS SELECT EMPNAME, CITY, GRADE FROM STAFFV2 WHERE EMPNAME >= 'Betty' AND EMPNUM < 'E35' OR CITY <= 'Deale' AND GRADE > 12 OR GRADE = 13 AND CITY <> 'Akron';
 CREATE VIEW UPDATE_VIEW8 AS SELECT MYTABLE.EMPNUM, MYTABLE.EMPNAME FROM STAFF MYTABLE WHERE MYTABLE.GRADE = 12;
 CREATE VIEW UPDATE_VIEW9 AS SELECT EMPNAME, CITY, GRADE FROM STAFF WHERE NOT EMPNAME >= 'Betty' AND EMPNUM <= 'E35' OR NOT (CITY <= 'Deale') AND GRADE > 9 AND NOT (GRADE = 13 AND CITY <> 'Akron') OR NOT CITY IN ('Vienna','New York','Deale');

COMMIT WORK;

 DELETE FROM UPDATE_VIEW1 WHERE CITY = 'Tampa';
 DELETE FROM UPDATE_VIEW1 WHERE CITY = 'Deale';
 SELECT COUNT (*) FROM PROJ;
-- PASS:0281 If count = 2?

ROLLBACK WORK;


 INSERT INTO UPDATE_VIEW2 VALUES (10, 'E9', 'P7');
 UPDATE UPDATE_VIEW2 SET HOURS = 10 WHERE EMPNUM = 'E4';
 SELECT COUNT (*) FROM WORKS WHERE HOURS = 10;
-- PASS:0281 If count = 3?

ROLLBACK WORK;

 UPDATE UPDATE_VIEW3 SET EMPNUM = 'E7' WHERE EMPNUM = 'E1';
 DELETE FROM UPDATE_VIEW3 WHERE HOURS = 80;
 SELECT COUNT (*) FROM WORKS WHERE EMPNUM = 'E7';
-- PASS:0281 If count = 2?

ROLLBACK WORK;

 DELETE FROM UPDATE_VIEW4 WHERE EMPNUM = 'E1';
 DELETE FROM UPDATE_VIEW4 WHERE EMPNUM = 'E3';
 SELECT COUNT (*) FROM WORKS;
-- PASS:0282 If count = 10?

ROLLBACK WORK;

 INSERT INTO UPDATE_VIEW5 VALUES ('E6',NULL,11,NULL);
 INSERT INTO UPDATE_VIEW5 VALUES ('E7',NULL,11,'Deale');
 INSERT INTO UPDATE_VIEW5 VALUES ('E8','Mary',11,NULL);
 DELETE FROM UPDATE_VIEW5;
 SELECT COUNT (*) FROM STAFF;
-- PASS:0282 If count = 7?

ROLLBACK WORK;

 UPDATE UPDATE_VIEW6 SET GRADE = 12 WHERE CITY = 'Vienna';
 DELETE FROM UPDATE_VIEW6 WHERE GRADE = 10;
 SELECT COUNT (*) FROM STAFF WHERE GRADE = 13;
-- PASS:0282 If count = 1?

ROLLBACK WORK;

 UPDATE UPDATE_VIEW7 SET GRADE = 15;
 DELETE FROM UPDATE_VIEW7 WHERE CITY = 'Akron';
 SELECT COUNT (*) FROM STAFF WHERE GRADE = 15;
-- PASS:0283 If count = 1?

ROLLBACK WORK;

 INSERT INTO UPDATE_VIEW8 VALUES ('E6','GEORGE');
 INSERT INTO UPDATE_VIEW8 VALUES ('E7','SHARA');
 INSERT INTO UPDATE_VIEW8 VALUES ('E8','DAVID');
 INSERT INTO UPDATE_VIEW8 VALUES ('E9','JOHNNY');
 UPDATE UPDATE_VIEW8 SET EMPNAME = 'Kathy';
 SELECT COUNT (*) FROM STAFF WHERE GRADE IS NULL OR EMPNAME = 'Kathy';
-- PASS:0283 If count = 6?

ROLLBACK WORK;

 DELETE FROM UPDATE_VIEW9 WHERE GRADE = 12;
 UPDATE UPDATE_VIEW9 SET GRADE = 15;
 SELECT COUNT (*) FROM STAFF WHERE GRADE = 15;
-- PASS:0283 If count = 2?

DROP DATABASE;
