SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0039 COUNT DISTINCT function!
 INSERT INTO WORKS VALUES('E5','P5',NULL);
 SELECT COUNT(DISTINCT HOURS) FROM WORKS;
-- PASS:0039 If count = 4?
		
ROLLBACK;

 INSERT INTO WORKS VALUES('E5','P5',NULL);
 SELECT SUM(ALL HOURS) FROM WORKS;
-- PASS:0167 If SUM(ALL HOURS) = 464?

ROLLBACK;
 INSERT INTO WORKS VALUES('E5','P5',NULL);
 SELECT SUM(HOURS) FROM WORKS;
-- PASS:0168 If SUM(HOURS) = 464?

ROLLBACK;

-- TEST:0169 COUNT(*) function !
 INSERT INTO WORKS VALUES('E5','P5',NULL);
 SELECT COUNT(*) FROM WORKS;
-- PASS:0169 If count = 13?

ROLLBACK;

-- TEST:0040 SUM function with WHERE clause!
 SELECT SUM(HOURS) FROM WORKS WHERE PNUM = 'P2';
-- PASS:0040 If SUM(HOURS) = 140?

-- TEST:0170 SUM DISTINCT function with WHERE clause!
 SELECT SUM(DISTINCT HOURS) FROM WORKS WHERE PNUM = 'P2';
-- PASS:0170 If SUM(DISTINCT HOURS) = 100?

-- TEST:0171 SUM(column) + value!
 SELECT SUM(HOURS)+10 FROM WORKS WHERE PNUM = 'P2';
-- PASS:0171 If SUM(HOURS)+10 = 150?

-- TEST:0041 MAX function in subquery!
 SELECT EMPNUM FROM STAFF WHERE GRADE = (SELECT MAX(GRADE) FROM STAFF) ORDER BY EMPNUM;
-- PASS:0041 If 2 rows are selected and EMPNUMs = 'E3' and 'E5'?

-- TEST:0042 MIN function in subquery!
 SELECT EMPNUM FROM STAFF WHERE GRADE = (SELECT MIN(GRADE) FROM STAFF);
-- PASS:0042 If EMPNUM = 'E2'?

-- TEST:0043 AVG function!
 SELECT AVG(GRADE) FROM STAFF;
-- PASS:0043 If AVG(GRADE) = 12?

DROP DATABASE;
