SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

-- TEST:0129 Double quote work in character string literal!

 CREATE TABLE JJ (FLOATTEST  FLOAT);
 INSERT INTO STAFF VALUES('E8','Yang Ling',15,'Xi''an');
-- PASS:0129 If 1 row is inserted?

 SELECT GRADE,CITY FROM STAFF WHERE EMPNUM = 'E8';
-- Expected output:
--        GRADE CITY
-- ============ ===============
--           15 Xi'an

ROLLBACK WORK;

 INSERT INTO JJ VALUES(123.456E3);
 SELECT COUNT(*) FROM JJ WHERE FLOATTEST > 123455 AND FLOATTEST < 123457;
-- PASS:0130 If count = 1 ?

ROLLBACK WORK;

 INSERT INTO JJ VALUES(123456E-3);
 SELECT COUNT(*) FROM JJ WHERE FLOATTEST > 122 AND FLOATTEST < 124;
-- PASS:0131 If count = 1 ?

ROLLBACK WORK;

 INSERT INTO JJ VALUES(-123456E-3);
 SELECT COUNT(*) FROM JJ WHERE FLOATTEST > -124 AND FLOATTEST < -122;
-- PASS:0131 If count = 1 ?

ROLLBACK WORK;

DROP DATABASE;
