SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT WORK;

-- TEST:0393 SUM, MAX on Cartesian product!

 CREATE TABLE STAFF1 (EMPNUM    CHAR(3) NOT NULL, EMPNAME  CHAR(20), GRADE DECIMAL(4), CITY   CHAR(15));
 SELECT SUM(HOURS), MAX(HOURS) FROM STAFF, WORKS;
-- PASS:0393 If SUM(HOURS) = 2320 and MAX(HOURS) = 80?

 SELECT AVG(HOURS), MIN(HOURS) FROM STAFF, WORKS WHERE STAFF.EMPNUM = 'E2' AND STAFF.EMPNUM = WORKS.EMPNUM;
-- PASS:0394 If AVG(HOURS) = 60 and MIN(HOURS) = 40?

-- TEST:0395 SUM, MIN on joined table with GROUP without WHERE!
 SELECT STAFF.EMPNUM, SUM(HOURS), MIN(HOURS) FROM STAFF, WORKS GROUP BY STAFF.EMPNUM ORDER BY 1;
 
-- PASS:0395 If 5 rows are selected with the following order?
-- PASS:0395 STAFF.EMPNUM SUM(HOURS) MIN(HOURS)?
-- PASS:0395 'E1' 464 12?
-- PASS:0395 'E2' 464 12?
-- PASS:0395 'E3' 464 12?
-- PASS:0395 'E4' 464 12?
-- PASS:0395 'E5' 464 12?


-- TEST:0396 SUM, MIN on joined table with WHERE, GROUP BY, HAVING!
 SELECT STAFF.EMPNUM, AVG(HOURS), MIN(HOURS) FROM  STAFF, WORKS WHERE STAFF.EMPNUM IN ('E1','E4','E3') AND STAFF.EMPNUM = WORKS.EMPNUM GROUP BY STAFF.EMPNUM HAVING COUNT(*) > 1 ORDER BY STAFF.EMPNUM;
-- PASS:0396 If 2 rows are selected with the following order?
-- PASS:0396 STAFF.EMPNUM AVG(HOURS) MIN(HOURS)?
-- PASS:0396 'E1' 30 to 31 12?
-- PASS:0396 'E4' 46 to 47 20?

DROP DATABASE;
