SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;


 CREATE TABLE WORKS1(EMPNUM    CHAR(3) NOT NULL, PNUM    CHAR(3) NOT NULL, HOURS   DECIMAL(5), UNIQUE(EMPNUM, PNUM));

COMMIT;

-- TEST:0275 COMMIT and ROLLBACK of multiple tables!
 INSERT INTO STAFF1 SELECT * FROM STAFF;
 INSERT INTO WORKS1 SELECT * FROM WORKS;
 INSERT INTO PROJ1 SELECT * FROM PROJ;
 UPDATE STAFF1 SET EMPNUM = 'E9' WHERE EMPNUM = 'E3';
 UPDATE WORKS1 SET EMPNUM = 'E9', PNUM = 'P9' WHERE EMPNUM = 'E3';
 UPDATE PROJ1 SET PNUM = 'P9' WHERE PNUM = 'P2';
 COMMIT WORK;
 SELECT COUNT(*) FROM STAFF1,WORKS1,PROJ1 WHERE STAFF1.EMPNUM = 'E9' AND STAFF1.EMPNUM = WORKS1.EMPNUM AND PROJ1.PNUM = WORKS1.PNUM;
-- PASS:0275 If count = 1?


-- TEST:0279 IN is a 3-valued predicate, EXISTS is 2-valued!

 UPDATE WORKS SET HOURS = NULL WHERE PNUM = 'P5' OR EMPNUM = 'E4';
 SELECT COUNT(*) FROM STAFF;
-- PASS:0279 If count = 5?
 SELECT COUNT(*) FROM STAFF WHERE 40 IN (SELECT HOURS FROM WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM);
-- PASS:0279 If count = 2?
 SELECT COUNT(*) FROM STAFF WHERE 40 NOT IN (SELECT HOURS FROM WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM);
-- PASS:0279 If count = 2?
 SELECT COUNT(*) FROM STAFF WHERE EXISTS (SELECT * FROM WORKS WHERE HOURS = 40 AND STAFF.EMPNUM = WORKS.EMPNUM);
-- PASS:0279 If count = 2?
 SELECT COUNT(*) FROM STAFF WHERE NOT EXISTS (SELECT * FROM WORKS WHERE HOURS = 40 AND  STAFF.EMPNUM = WORKS.EMPNUM);
-- PASS:0279 If count = 3?


DROP DATABASE;
