SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0108 Search condition true OR NOT(true)!
 SELECT EMPNUM,CITY FROM   STAFF WHERE  EMPNUM='E1' OR NOT(EMPNUM='E1');
-- PASS:0108 If 5 rows are selected ?

-- TEST:0109 Search condition true AND NOT(true)!
 SELECT EMPNUM,CITY FROM   STAFF WHERE  EMPNUM='E1' AND NOT(EMPNUM='E1');
-- PASS:0109 If 0 rows are selected ?

-- TEST:0110 Search condition unknown OR NOT(unknown)!
 INSERT INTO WORKS VALUES('E8','P8',NULL);
 SELECT EMPNUM,PNUM FROM WORKS WHERE HOURS < (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8') OR NOT(HOURS < (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8'));
-- PASS:0110 If 0 rows are selected ?

ROLLBACK;

-- TEST:0111 Search condition unknown AND NOT(unknown)!
 INSERT INTO WORKS VALUES('E8','P8',NULL);
 SELECT EMPNUM,PNUM FROM WORKS WHERE HOURS < (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8') AND NOT(HOURS< (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8'));
-- PASS:0111 If 0 rows are selected?

ROLLBACK;

-- TEST:0112 Search condition unknown AND true!
 INSERT INTO WORKS VALUES('E8','P8',NULL);
 SELECT EMPNUM,PNUM FROM WORKS WHERE HOURS < (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8') AND   HOURS IN (SELECT HOURS FROM WORKS);
-- PASS:0112 If 0 rows are selected?

ROLLBACK;

-- TEST:0113 Search condition unknown OR true!
 INSERT INTO WORKS VALUES('E8','P8',NULL);
 SELECT EMPNUM,PNUM FROM WORKS WHERE HOURS < (SELECT HOURS FROM WORKS WHERE EMPNUM = 'E8') OR    HOURS IN (SELECT HOURS FROM WORKS) ORDER BY EMPNUM;
-- PASS:0113 If 12 rows are selected?
-- PASS:0113 If first EMPNUM = 'E1'?

DROP DATABASE;
