SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0637 Feature 14, Qualified * in select list (static)!
 CREATE VIEW QUALSTAR AS SELECT STAFF.*, HOURS FROM STAFF, WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM; 
 CREATE VIEW CORRQUALSTAR AS SELECT BLAH.*, HOURS FROM STAFF BLAH, WORKS WHERE BLAH.EMPNUM = WORKS.EMPNUM; 
 CREATE VIEW SUBQ2 AS SELECT DISTINCT * FROM QUALSTAR;
 CREATE VIEW CORRSUBQ2 AS SELECT DISTINCT * FROM CORRQUALSTAR;
 SELECT COUNT(*) FROM QUALSTAR;
-- PASS:0637 If count = 12?
 SELECT COUNT(*) FROM SUBQ2;
-- PASS:0637 If count = 10?
 SELECT EMPNUM, GRADE, CITY, HOURS FROM QUALSTAR WHERE EMPNAME = 'Carmen'; 
-- PASS:0637 If 1 row selected and EMPNUM = 'E3' and GRADE = 13?
-- PASS:0637 AND CITY = 'Vienna' and HOURS = 20?
 SELECT STAFF.*, HOURS FROM STAFF, WORKS WHERE STAFF.EMPNUM = WORKS.EMPNUM AND EMPNAME = 'Carmen'; 
-- PASS:0637 If 1 row selected and EMPNUM = 'E3' and EMPNAME = 'Carmen'?
-- PASS:0637 AND GRADE = 13 and CITY = 'Vienna' and HOURS = 20?
 SELECT COUNT(*) FROM CORRQUALSTAR; 
-- PASS:0637 If count = 12?
 SELECT COUNT(*) FROM CORRSUBQ2; 
 -- PASS:0637 If count = 10?
 SELECT EMPNUM, GRADE, CITY, HOURS FROM CORRQUALSTAR WHERE EMPNAME = 'Carmen'; 
-- PASS:0637 If 1 row selected and EMPNUM = 'E3'?
-- PASS:0637 AND GRADE = 13 and CITY = 'Vienna' and HOURS = 20?

 CREATE TABLE FEAT16 ( EMPNUM INT NOT NULL PRIMARY KEY, PNUM   INT UNIQUE); 
 CREATE TABLE BARNO ( P1 INT NOT NULL, P2 CHAR NOT NULL, X1 INT, X2 CHAR, UNIQUE (X2, X1), PRIMARY KEY (P1, P2)); 
 INSERT INTO FEAT16 VALUES (1, 10); 
 INSERT INTO FEAT16 VALUES (2, 20); 
 INSERT INTO FEAT16 VALUES (1, 30); 
--  PASS:0641 If ERROR, unique constraint, 0 rows inserted?
 INSERT INTO FEAT16 VALUES (3, 20);
--  PASS:0641 If ERROR, unique constraint, 0 rows inserted?
 INSERT INTO FEAT16 VALUES (3, NULL);
 INSERT INTO FEAT16 VALUES (4, NULL);
 INSERT INTO FEAT16 VALUES (5, NULL);
 INSERT INTO BARNO VALUES (1, 'A', 10, 'a');
 INSERT INTO BARNO VALUES (2, 'A', 20, 'a');
 INSERT INTO BARNO VALUES (1, 'A', 30, 'a');
--  PASS:0641 If ERROR, unique constraint, 0 rows inserted?
 INSERT INTO BARNO VALUES (3, 'A', 20, 'a');
--  PASS:0641 If ERROR, unique constraint, 0 rows inserted?
 INSERT INTO BARNO VALUES (3, NULL, 30, 'a');
--  PASS:0641 If ERROR, PRIMARY KEY constraint, 0 rows inserted?
--  PASS:0641 OR ERROR, NOT NULL constraint, 0 rows inserted?
 INSERT INTO BARNO VALUES (3, NULL, 30, 'b');
--  PASS:0641 If ERROR, PRIMARY KEY constraint, 0 rows inserted?
--  PASS:0641 OR ERROR, NOT NULL constraint, 0 rows inserted?
 INSERT INTO BARNO VALUES (3, 'A', 30, NULL);
-- PASS:0641 If 1 row is inserted?
 INSERT INTO BARNO VALUES (3, 'B', 30, NULL);
--  test doc says this should pass, but we already have a value of
--  30, null for x1, x2 in the database. I think it should fail. It
--  does fail for Firebird 1.5.
--  PASS:0641 If 1 row is inserted?
 INSERT INTO BARNO VALUES (4, 'B', NULL, NULL);
-- PASS:0641 If 1 row is inserted?

DROP DATABASE;
