SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

 CREATE DOMAIN EPOCH_NOT_NORM AS DECIMAL (5, 2);
 CREATE DOMAIN RAD_EPOCH_TYPE FLOAT (20) CHECK (VALUE BETWEEN 0E0 AND 2E0 * 3.1416E0); 
 CREATE DOMAIN RAD_EPOCH_NOT_NORM REAL;
 CREATE DOMAIN TIDEDATE AS DATE CHECK (VALUE BETWEEN DATE '1994-01-01' AND DATE '2025-12-31'); 
 CREATE DOMAIN DINNERTIME AS TIME CHECK (VALUE BETWEEN TIME '17:30:00' AND TIME '19:00:00'); 
 CREATE TABLE DINNER_CLUB ( LOC_ID DEC (7) NOT NULL, DINNER DINNERTIME); 
 INSERT INTO DINNER_CLUB VALUES (0, TIME '17:30:00'); 
 INSERT INTO DINNER_CLUB VALUES (2, TIME '19:30:00');
-- PASS:0860 If ERROR - integrity constraint violation?

DROP DATABASE;
