SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0599 UNION in views (feature 8) (static)!
 CREATE TABLE USIG (C1 INT, C_1 INT);
 INSERT INTO USIG VALUES (0,2);
 INSERT INTO USIG VALUES (1,3);
 CREATE VIEW UUSIG (U1) AS SELECT C1 FROM USIG UNION SELECT C_1 FROM USIG; 
-- PASS:0599 If view is created?
 SELECT COUNT(*) FROM UUSIG;
-- PASS:0599 If count = 4?
 SELECT COUNT(DISTINCT U1) FROM UUSIG;
-- PASS:0599 If count = 4?
 SELECT COUNT(*) FROM UUSIG WHERE U1 < 0 OR U1 > 3 OR U1 IS NULL;
-- PASS:0599 If count = 0?
 CREATE VIEW ABOVE_AVERAGE (COLUMN_1, COLUMN_2, COLUMN_3) AS SELECT PNUM, BUDGET, CITY FROM PROJ OUTER_REF WHERE BUDGET >= (SELECT AVG(BUDGET) FROM PROJ INNER_REF WHERE OUTER_REF.CITY = INNER_REF.CITY) UNION SELECT 'MAX', MAX(BUDGET), MIN(CITY) FROM PROJ  WHERE CITY > 'Deale'; 
-- PASS:0599 If view is created?
 SELECT * FROM ABOVE_AVERAGE ORDER BY COLUMN_1;
-- PASS:0599 If 4 rows selected with ordered rows and column values: ?
-- PASS:0599 MAX 30000 Tampa ?
-- PASS:0599 P2 30000 Vienna ?
-- PASS:0599 P3 30000 Tampa ?
-- PASS:0599 P6 50000 Deale ?
 CREATE VIEW FOUR_CITIES (C1, C2, C3) AS SELECT 'P', CITY, 666   FROM PROJ  WHERE BUDGET <> 30000 UNION SELECT 'S', CITY, 777  FROM STAFF  WHERE EMPNAME <> 'Ed' UNION SELECT 'T', CITY, -999   FROM STAFF3   WHERE CITY NOT LIKE 'V%' UNION SELECT 'X', CITY, -1  FROM STAFF3  WHERE CITY = 'Vienna'; 
-- PASS:0599 If view is created?
 SELECT C2, C1, C3 FROM FOUR_CITIES ORDER BY C3, C2;
-- PASS:0599 If 7 rows selected with ordered rows and column values ?
-- PASS:0599 Akron T -999 ?
-- PASS:0599 Deale T -999 ?
-- PASS:0599 Vienna X -1 ?
-- PASS:0599 Deale P 666 ?
-- PASS:0599 Vienna P 666 ?
-- PASS:0599 Deale S 777 ?
-- PASS:0599 Vienna S 777 ?
 SELECT COUNT (*) FROM FOUR_CITIES;
-- PASS:0599 If count = 7 ?
 SELECT COUNT(*) FROM FOUR_CITIES WHERE C3 > 0; 
-- PASS:0599 If count = 4 ?
 SELECT COUNT(*) FROM FOUR_CITIES WHERE C2 = 'Vienna';
-- PASS:0599 If count = 3 ?

-- TEST:0601 DATETIME data types (feature 5) (static)!
 CREATE TABLE TSSMALL ( SMALLD DATE, SMALLT TIME, SMALLTS TIMESTAMP);
 INSERT INTO TSSMALL VALUES ( CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP); 
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (YEAR FROM SMALLD) = EXTRACT (YEAR FROM SMALLTS);
-- PASS:0613 If count = 1?
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (MONTH FROM SMALLD) = EXTRACT (MONTH FROM SMALLTS); 
-- PASS:0613 If count = 1?
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (DAY FROM SMALLD) = EXTRACT (DAY FROM SMALLTS); 
-- PASS:0613 If count = 1?
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (HOUR FROM SMALLT) = EXTRACT (HOUR FROM SMALLTS); 
-- PASS:0613 If count = 1?
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (MINUTE FROM SMALLT) = EXTRACT (MINUTE FROM SMALLTS); 
-- PASS:0613 If count = 1?
 SELECT COUNT(*) FROM TSSMALL WHERE EXTRACT (SECOND FROM SMALLT) - EXTRACT (SECOND FROM SMALLTS) > -1 AND EXTRACT (SECOND FROM SMALLT) - EXTRACT (SECOND FROM SMALLTS) < 1; 
-- PASS:0613 If count = 1?

DROP DATABASE;
