SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

INPUT ddl/input/base-tab.sql;
COMMIT;

-- TEST:0866 Case expressions in other than SELECT!

 CREATE VIEW V0866 (EMPNUM, HOURS) AS SELECT EMPNUM, CASE WHEN PNUM = 'P2' THEN HOURS + 30 ELSE HOURS END FROM WORKS;
 UPDATE STAFF SET CITY = NULLIF (CITY, 'Deale'); 
 SELECT COUNT(*) FROM STAFF WHERE CITY IS NULL; 
-- PASS:0866 If COUNT = 2?

 INSERT INTO STAFF VALUES ( 'E8', 'Wally', CASE WHEN USER = 'SYSDBA' THEN 15 ELSE 10 END, 'Monash');
 SELECT COUNT(*) FROM STAFF WHERE GRADE = 15; 
-- PASS:0866 If COUNT = 1?

 SELECT COUNT(*) FROM STAFF WHERE CASE GRADE WHEN 10 THEN 12 WHEN 13 THEN 12 END = 12;
-- PASS:0866 If COUNT = 3?

 SELECT SUM(HOURS) FROM V0866;
-- PASS:0866 If SUM(HOURS) = 584?

 SELECT COALESCE (CITY, EMPNUM) FROM STAFF ORDER BY 1;
-- PASS:0866 If 6 rows are returned in the following order?
--               coalesce(city,empnum)
--               =====================
-- PASS:0866 If Akron?
-- PASS:0866 If E1 ?
-- PASS:0866 If E4 ?
-- PASS:0866 If Monash?
-- PASS:0866 If Vienna?
-- PASS:0866 If Vienna?

DROP DATABASE;
