SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

-- References to schemas in the SDL series have been removed, since
-- Firebird doesn't support them. However, this kind of defeats the 
-- purpose of these tests. 6/16/2005.

INPUT ddl/input/base-tab.sql;
COMMIT;

CREATE TABLE TEMP_OBSERV (
   YEAR_OBSERV NUMERIC(4),
   CITY CHAR(10),
   MAX_TEMP NUMERIC(5,2),
   MIN_TEMP     NUMERIC(5,2));
   
 INSERT INTO TEMP_OBSERV VALUES (1984, 'Sun City', 110, 44);
 INSERT INTO TEMP_OBSERV VALUES (1984, 'Iceburg', 45, -90);
 INSERT INTO TEMP_OBSERV VALUES (1984, 'Abeland', 101, 10);
 INSERT INTO TEMP_OBSERV VALUES (1985, 'Sun City', 105, 50);
 INSERT INTO TEMP_OBSERV VALUES (1985, 'Iceburg', 47, -82);
 INSERT INTO TEMP_OBSERV VALUES (1985, 'Abeland', 98, -3);
 CREATE VIEW CELSIUS_OBSERV (CITY, YEAR_OBSERV, MIN_C, MAX_C) AS SELECT CITY, YEAR_OBSERV, (MIN_TEMP - 32) * 5 / 9, (MAX_TEMP - 32) * 5 / 9 FROM TEMP_OBSERV; 
 CREATE VIEW MULTI_YEAR_OBSERV (CITY, HIGH, LOW) AS SELECT CITY, AVG(MAX_TEMP), AVG(MIN_TEMP) FROM TEMP_OBSERV GROUP BY CITY;
 CREATE VIEW EXTREME_TEMPS (YEAR_OBSERV, HIGH, LOW) AS SELECT YEAR_OBSERV, MAX(MAX_TEMP), MIN(MIN_TEMP) FROM TEMP_OBSERV GROUP BY YEAR_OBSERV; 
-- TEST:0391 Correlation names used in self-join of view!

 SELECT X.CITY, X.MAX_C, Y.MAX_C, (X.MAX_C + Y.MAX_C) / 2 FROM CELSIUS_OBSERV X, CELSIUS_OBSERV Y WHERE X.YEAR_OBSERV = 1984 AND Y.YEAR_OBSERV = 1985 AND X.CITY = Y.CITY ORDER BY 4 DESC; 
-- PASS:0391 If for the first row X.CITY = 'Sun City',?
-- PASS:0391 X.MAX_C is between 43.31 and 43.35,?
-- PASS:0391 Y.MAX_C is between 40.54 and 40.57?
-- PASS:0391 and (X.MAX_C + Y.MAX_C) /2 is between 41.93 and 41.96?

 SELECT CITY, YEAR_OBSERV, MIN_C, MAX_C FROM CELSIUS_OBSERV WHERE YEAR_OBSERV = 1984 AND MIN_C > 5; 
-- PASS:0401 If CITY = 'Sun City' and YEAR_OBSERV = 1984?
-- PASS:0401 If MIN_C is between 6.65 and 6.68?
-- PASS:0401 If MAX_C is between 43.31 and 43.35?

 SELECT CITY, HIGH, LOW FROM MULTI_YEAR_OBSERV ORDER BY CITY ASC; 
-- PASS:0401 If for the first row HIGH is between 99.3 and 99.7?
-- PASS:0401 and LOW is between 3.3 and 3.7?

 SELECT HIGH, YEAR_OBSERV, LOW  FROM EXTREME_TEMPS ORDER BY YEAR_OBSERV DESC; 
-- PASS:0401 If for the first row HIGH = 105 and LOW = -82?

DROP DATABASE;
