CREATE DATABASE 'test.fdb' ;
CREATE TABLE test( id INTEGER NOT NULL CONSTRAINT unq UNIQUE,
                   text VARCHAR(32));
SET TERM ^;
CREATE TRIGGER tg FOR test BEFORE UPDATE
AS
BEGIN
  old.id=1;
END ^
SET TERM ;^

ALTER TRIGGER tg AFTER DELETE;
SHOW TRIGGER tg;

DROP DATABASE;

