SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;
		
CREATE TABLE TABLEEXISTS (COL CHAR(10));
		
INSERT INTO TABLEEXISTS VALUES('Hello');
-- this should fail, in use
CREATE INDEX INDEXEXISTS ON TABLEEXISTS(COL);

commit;	
		
CREATE VIEW VIEWEXISTS AS SELECT * FROM TABLEEXISTS;

commit;

-- this should pass
CREATE INDEX INDEXEXISTS ON TABLEEXISTS(COL);

-- this should fail, duplicate entry
CREATE INDEX INDEXEXISTS ON TABLEEXISTS(COL);

drop database ;
