-- S0347108
-- PORTAL TEST PROGRAM REGRESSION

set names ascii;
create database 'test.fdb';
create table USER_DATA (
    BASE_DATA_ID bigint not null,
    OWNER_IDENTITY_ID bigint,
    primary key (BASE_DATA_ID)
);
create table tbl_IDENTITY (
    IDENTITY_ID bigint not null,
    OBJECT_VERSION bigint not null,
    IS_ACTIVE char(1),
    IS_GROUP char(1),
    OMRID varchar(80) not null unique,
    NAME varchar(80) not null,
    IDENTITY_PROXY_ID bigint unique,
    primary key (IDENTITY_ID)
);


create table PERMISSION (
    PERMISSION_ID bigint not null,
    OBJECT_VERSION bigint not null,
    READ_PERM smallint,
    WRITE_PERM smallint,
    IDENTITY_ID bigint,
    BASE_DATA_ID bigint,
    primary key (PERMISSION_ID)
);


CREATE TABLE IDENTITY_GROUP_HIERARCHY (
   SESSION_ID BIGINT NOT NULL,
   IDENTITY_ID BIGINT NOT NULL,
   GROUP_ID BIGINT NOT NULL,
   HLEVEL SMALLINT NOT NULL
);


CREATE VIEW USER_OBJECT_PERMS (SESSION_ID, USER_ID, GROUP_ID, HLEVEL, OBJECT_ID, READ_PERM, WRITE_PERM) AS

SELECT G.SESSION_ID, G.IDENTITY_ID, G.GROUP_ID, G.HLEVEL, P.BASE_DATA_ID, P.READ_PERM, P.WRITE_PERM
FROM IDENTITY_GROUP_HIERARCHY G, PERMISSION P
WHERE G.GROUP_ID = P.IDENTITY_ID AND (P.WRITE_PERM IS NOT NULL OR P.READ_PERM IS NOT NULL);



set term ^;

CREATE PROCEDURE "USER_DATA_PERMISSIONS" 
(
  "SESSION_ID" BIGINT,
  "OBJECT_ID" BIGINT,
  "PERM_TYPE" SMALLINT
)
RETURNS
(
  "PERM" SMALLINT
)
AS
BEGIN
   IF(PERM_TYPE = 1) THEN
      BEGIN
         SELECT MIN(READ_PERM)
         FROM USER_OBJECT_PERMS
            WHERE SESSION_ID = :SESSION_ID AND OBJECT_ID = :OBJECT_ID
            AND HLEVEL = (SELECT MIN(HLEVEL) FROM USER_OBJECT_PERMS WHERE SESSION_ID = :SESSION_ID AND OBJECT_ID = :OBJECT_ID)
         INTO :PERM;
      END
   ELSE
      BEGIN
         IF(PERM_TYPE = 2) THEN
            BEGIN
               SELECT MIN(WRITE_PERM)
               FROM USER_OBJECT_PERMS
                  WHERE SESSION_ID = :SESSION_ID AND OBJECT_ID = :OBJECT_ID
                  AND HLEVEL = (SELECT MIN(HLEVEL) FROM USER_OBJECT_PERMS WHERE SESSION_ID = :SESSION_ID AND OBJECT_ID = :OBJECT_ID)
               INTO :PERM;
            END
      END
   SUSPEND;
END^


CREATE PROCEDURE "OBJECT_PERMISSIONS" 
(
  "SESSION_ID" BIGINT,
  "OBJECT_ID" BIGINT,
  "PERM_TYPE" SMALLINT
)
RETURNS
(
  "PERM" SMALLINT
)
AS
   DECLARE VARIABLE PROXY_ID BIGINT;
BEGIN
   SELECT PERM FROM USER_DATA_PERMISSIONS(:SESSION_ID, :OBJECT_ID, :PERM_TYPE)
   INTO :PERM;

   IF (PERM IS NULL) THEN
      BEGIN
         SELECT ident.IDENTITY_PROXY_ID
         FROM USER_DATA ud
         JOIN tbl_IDENTITY ident on ud.OWNER_IDENTITY_ID = ident.IDENTITY_ID
            WHERE ud.BASE_DATA_ID = :OBJECT_ID
         INTO :PROXY_ID;

         IF (PROXY_ID IS NOT NULL) THEN
            BEGIN
               SELECT PERM FROM USER_DATA_PERMISSIONS(:SESSION_ID, :PROXY_ID, :PERM_TYPE)
               INTO :PERM;
            END
      END
   SUSPEND;
END^

set term ; ^


 select perm from OBJECT_PERMISSIONS(0,248,2);  
 
 drop database;
 