CREATE DATABASE 'test.fdb' ;
CREATE TABLE test( id INTEGER NOT NULL CONSTRAINT pk PRIMARY KEY,
                   text VARCHAR(32));

ALTER TABLE test DROP CONSTRAINT pk;
SHOW TABLE test;

DROP DATABASE;

