CREATE DATABASE 'test.fdb' ;
CREATE TABLE fk(id INT NOT NULL PRIMARY KEY);

CREATE TABLE test(
 c1 SMALLINT NOT NULL,
 c2 INTEGER DEFAULT 0,
 c3 FLOAT NOT NULL UNIQUE,
 c4 DOUBLE PRECISION NOT NULL PRIMARY KEY,
 c5 INT REFERENCES fk(id),
 c6 INT CHECK (c6>c5),
 c7 COMPUTED (c1+c2),
 c8 CHAR(31) DEFAULT USER,
 c9 VARCHAR(40) DEFAULT 'data'
);
SHOW TABLE test;


DROP DATABASE;

