CREATE DATABASE 'test.fdb' ;
CREATE TABLE fk(id INT NOT NULL PRIMARY KEY);

CREATE TABLE test(
 c1 SMALLINT NOT NULL,
 c2 SMALLINT NOT NULL,
 c3 SMALLINT NOT NULL,
 PRIMARY KEY(c1),
 UNIQUE(c2),
 FOREIGN KEY (c2) REFERENCES fk(id) ON DELETE CASCADE,
 CHECK (c2>c1),
 CONSTRAINT test UNIQUE(c3),
 CONSTRAINT test2 FOREIGN KEY (c3) REFERENCES fk(id) ON DELETE SET NULL,
 CONSTRAINT test3 CHECK (NOT c3>c1)
);
SHOW TABLE test;

DROP DATABASE;

