CREATE DATABASE 'test.fdb' ;
CREATE DOMAIN test VARCHAR(32765)[40000];

CREATE TABLE test(
 c1 VARCHAR(40) CHARACTER SET CYRL COLLATE CYRL,
 c2 VARCHAR(40) CHARACTER SET DOS437 COLLATE DB_DEU437,
 c3 BLOB SUB_TYPE TEXT CHARACTER SET DOS437,
 c4 test
);
SHOW TABLE test;


DROP DATABASE;

