SET NAMES ASCII;
CREATE DATABASE 'test.fdb' DEFAULT CHARACTER SET ISO8859_1;

 CREATE TABLE STAFF8 (EMPNUM char(3) character set utf16 NOT NULL, EMPNAME  char(20) character set utf16, GRADE DECIMAL(4), CITY char(15) character set utf16, PRIMARY KEY (EMPNUM), CHECK (EMPNAME IS NOT NULL));
 INSERT INTO STAFF8 VALUES('E1','Alice',34,'Deale');
 UPDATE STAFF8 SET EMPNAME = NULL WHERE EMPNUM = 'E1';
 SELECT COUNT(*) FROM STAFF8 WHERE EMPNAME = 'Alice';
 CREATE TABLE STAFF13 (EMPNUM    char(3) character set utf16 NOT NULL, EMPNAME  char(20) character set utf16, GRADE DECIMAL(4), CITY   char(15) character set utf16, PRIMARY KEY (EMPNUM), CHECK (NOT EMPNAME IS NULL) );
 INSERT INTO STAFF13 VALUES('E1','Alice',36,'Deale');
 UPDATE STAFF13 SET EMPNAME = NULL WHERE EMPNUM = 'E1';
 SELECT COUNT(*) FROM STAFF13 WHERE EMPNAME = 'Alice';
 CREATE TABLE STAFF9 (EMPNUM    char(3) character set utf16 NOT NULL PRIMARY KEY, EMPNAME  char(20) character set utf16, GRADE DECIMAL(4), CITY   char(15) character set utf16, CHECK (EMPNAME NOT LIKE 'T%'));
 INSERT INTO STAFF9 VALUES('E3','Susan',11,'Hawaii');
 UPDATE STAFF9 SET EMPNAME = 'Thomas' WHERE EMPNUM = 'E3';
 SELECT COUNT(*) FROM STAFF9 WHERE EMPNAME = 'Susan';

DROP DATABASE;
