CREATE DATABASE 'test.fdb' ;
SET NAMES ASCII;
CREATE EXCEPTION test 'message to show';

ALTER EXCEPTION test 'new message';
COMMIT;
SELECT RDB$EXCEPTION_NAME, RDB$EXCEPTION_NUMBER, cast(RDB$MESSAGE as varchar(15)) FROM RDB$EXCEPTIONS;

DROP DATABASE;

