CREATE DATABASE 'test.fdb' ;
SET NAMES ASCII;
CREATE EXCEPTION test 'message to show';
COMMIT;

SELECT RDB$EXCEPTION_NAME, RDB$EXCEPTION_NUMBER, cast(RDB$MESSAGE as varchar(15)) FROM RDB$EXCEPTIONS;

DROP DATABASE;

