CREATE DATABASE 'test.fdb' ;

show generators;

CREATE GENERATOR test;
COMMIT;
SELECT RDB$GENERATOR_NAME, RDB$SYSTEM_FLAG FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='TEST';

CREATE GENERATOR test2;
COMMIT;
SELECT RDB$GENERATOR_NAME, RDB$SYSTEM_FLAG FROM RDB$GENERATORS WHERE RDB$GENERATOR_NAME='TEST2';

SHOW GENERATORS;

drop generator test;
drop generator test2;

show generators;

DROP DATABASE;

